services:
  - type: web
    name: blog-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: blog-backend
          property: port
    healthCheckPath: /api/health